version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: test_script.sh 
      timeout: 30
      runas: root
  AfterInstall:
    - location: test_script.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: test_script.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: test_script.sh
      timeout: 30
      runas: root
